require: 
  - rubocop-rspec
  - rubocop-performance

AllCops:
  # Ruby 2.7 is the MINIMUM Ruby version supported
  TargetRubyVersion: '2.7.0'
  Exclude:
    - vendor/**/*

RSpec/MultipleExpectations:
  Max: 2